services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    links:
      - php
      - node

  php:
    build:
      dockerfile: ./docker/php.Dockerfile
    volumes:
      - ./:/var/www
    links:
      - mysql
      - node

  mysql:
    image: mysql:8.0
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: raw-blog
    ports:
      - "3306:3306"

  node:
    image: node:20.18.0-alpine
    ports:
      - "3000:3000"
    volumes:
      - ./:/var/www
    working_dir: /var/www
    tty: true

volumes:
  database: